basePath: /
consumes:
- application/json
info:
  description: |-
    Product API
    Documentation
  version: 1.0.0
paths:
  /products:
    get:
      operationId: listProducts
      tags:
      - products
produces:
- application/json
schemes:
- http
swagger: "2.0"
