// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GRPCServiceError g RPC service error
//
// swagger:model GRPCServiceError
type GRPCServiceError struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this g RPC service error
func (m *GRPCServiceError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this g RPC service error based on context it is used
func (m *GRPCServiceError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GRPCServiceError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GRPCServiceError) UnmarshalBinary(b []byte) error {
	var res GRPCServiceError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
