// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GrpcError GrpcError means that request to gRPC service failed.
//
// swagger:model GrpcError
type GrpcError struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this grpc error
func (m *GrpcError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this grpc error based on context it is used
func (m *GrpcError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GrpcError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GrpcError) UnmarshalBinary(b []byte) error {
	var res GrpcError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
