// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProductNotFoundError product not found error
//
// swagger:model ProductNotFoundError
type ProductNotFoundError struct {

	// ID
	ID int64 `json:"id,omitempty"`
}

// Validate validates this product not found error
func (m *ProductNotFoundError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this product not found error based on context it is used
func (m *ProductNotFoundError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductNotFoundError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductNotFoundError) UnmarshalBinary(b []byte) error {
	var res ProductNotFoundError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
