// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ValidationErrors ValidationErrors is a collection of validation error messages.
//
// swagger:model ValidationErrors
type ValidationErrors struct {

	// messages
	Messages []string `json:"messages"`
}

// Validate validates this validation errors
func (m *ValidationErrors) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this validation errors based on context it is used
func (m *ValidationErrors) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidationErrors) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidationErrors) UnmarshalBinary(b []byte) error {
	var res ValidationErrors
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
